#!/usr/bin/env python
"""Which rows print "Melee weapon", so a reach weapon can reach on them.

    uv run scripts/reaches.py            report the split
    uv run scripts/reaches.py --emit     write engine/_weapon_reach.py

A melee range is one of two different things and the decorator cannot tell them
apart. "Melee weapon" means **the reach of whatever is in your hand**, so a glaive
swings two squares; "Melee 1", "Melee touch" and "Melee 2" are fixed numbers that a
reach weapon does not change. Both arrive in content as `Melee(1)`.

The compendium knows, in `power.reach`:

    melee weapon   866      the weapon's reach
    melee          157      the weapon's reach
    melee 1        171      fixed
    melee touch    144      fixed
    melee 2          8      fixed
    melee 5          2      fixed

So this emits the first two as a set of refs that `dsl._reach_of` consults, and
everything else keeps its printed number. Generated rather than hand-written on 1,023
decorators, and committed as plain data inside `engine/` so that nothing has to import
`content` to read it -- the component file allows five `engine` -> `content` sites and
forbids a sixth.

**The alternative was `max(weapon, printed)` and Camille is right that it is wrong.**
It reads correctly on the 1,023 weapon rows and over-extends the 325 fixed ones: a
"Melee touch" row would stretch to two squares in a glaive's hand, which no printed
line says.

For a row written from here on, the convention is the same one `spec.py` already
hands the author: a brief saying "melee weapon" wants the ref in this set. Re-run
`--emit` after importing new rows.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from combat_engine.content.loader import game

OUT = Path(__file__).resolve().parents[1] / "src" / "combat_engine" / "engine" / "_weapon_reach.py"

#: Printed ranges whose reach is the wielded weapon's rather than a number.
BY_WEAPON = ("melee weapon", "melee")

#: "Melee weapon +1 reach" -- the weapon's reach *plus* what the card grants.
BONUS = re.compile(r"^melee weapon \+(\d+) reach$")


def split() -> tuple[set[str], dict[str, int], dict[str, int]]:
    db = game()
    counts: dict[str, int] = {}
    refs: set[str] = set()
    bonus: dict[str, int] = {}
    for ref, reach in db.execute(
        "SELECT ref, reach FROM power WHERE reach LIKE '%elee%'"
    ):
        text = (reach or "").strip().lower()
        counts[text] = counts.get(text, 0) + 1
        if text in BY_WEAPON:
            refs.add(ref)
        elif (plus := BONUS.match(text)):
            refs.add(ref)
            bonus[ref] = int(plus.group(1))
    return refs, counts, bonus


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--emit", action="store_true", help="write the data module")
    args = ap.parse_args()
    refs, counts, bonus = split()
    print(f"{'printed range':<24} {'rows':>6}  reach comes from")
    for text, n in sorted(counts.items(), key=lambda kv: -kv[1]):
        how = ("the weapon" if text in BY_WEAPON
               else "the weapon, plus what the card grants" if BONUS.match(text)
               else "the printed number")
        print(f"{text:<24} {n:>6}  {how}")
    print(f"\n{len(refs)} refs take their melee reach from the weapon, "
          f"{len(bonus)} of them with a printed bonus")
    if args.emit:
        body = "\n".join(f'    "{r}",' for r in sorted(refs))
        gives = "\n".join(f'    "{r}": {n},' for r, n in sorted(bonus.items()))
        OUT.write_text(
            '"""Rows whose printed melee range is "Melee weapon".\n\n'
            "Generated by `scripts/reaches.py --emit`; do not hand-edit. See that\n"
            "script for why this exists and why `max(weapon, printed)` was wrong.\n\n"
            "Plain data, and inside `engine/` deliberately: `dsl._reach_of` has to read\n"
            "it on every targeting question, and importing `content` to get it would be\n"
            "a sixth `engine` -> `content` site where the component file allows five.\n"
            '"""\n\n'
            "from __future__ import annotations\n\n"
            "#: A melee range on one of these takes its reach from the wielded weapon.\n"
            "#: Every other melee row keeps the number it prints.\n"
            "BY_WEAPON: frozenset[str] = frozenset((\n" + body + "\n))\n\n"
            "#: Rows printing \"Melee weapon +N reach\": N squares on top of the\n"
            "#: weapon's own. Dropped on the floor until it was read off the card --\n"
            "#: the range said \"melee weapon\" and the bonus was never extracted, so\n"
            "#: these reached one or two squares less than they print.\n"
            "GIVES: dict[str, int] = {\n" + gives + "\n}\n"
        )
        print(f"written to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
